name: Perform Unreleased Audit

on:
  workflow_dispatch:
  schedule:
  - cron: '0 16 * * 1'

jobs:
  audit:
    name: Perform Unreleased Audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # tag: v3.3.0
      with:
        ref: main
    - name: Check unreleased commits
      uses: ./
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        UNRELEASED_GITHUB_APP_CREDS: ${{ secrets.UNRELEASED_GITHUB_APP_CREDS }}
        ACTION_TYPE: 'unreleased'